### ISSUE TITLE
inspect Excel output file.

### ISSUE THREAD

**Issue by eliyabar** [flashxyz/DNA_sequencing_learning#1]
Please inspect this output.
it's enough?  we need more chart details? does it meet the requirements?

https://github.com/flashxyz/DNA_sequencing_learning/blob/master/VectorToHistograms/output.xlsx

**Comment by rotemsd** [comment]
what is mean the negative values?

**Comment by eliyabar** [comment]
As Hassin said:
Normalization = (X-avg)/Sigma
if the value exceeds 3 set it to 3
and if the value is beneath -3 , set it to -3
Did i get something wrong?

**Comment by rotemsd** [comment]
No.
You did fine.
I understand now.
