### ISSUE TITLE
Windows modification

### ISSUE THREAD

**Issue by eliyabar** [flashxyz/DNA_sequencing_learning#2]
We need to ask Hassin about adding windows together.
Now we work on window of 100, but when i make the graph, we decided to limit the max possible output to 1000.
if we make windows of 10000, 50000  etc.. we will get much higher max possible number than 1000.

**Comment by rotemsd** [comment]
If we normalized the data, there is meaning to window size?

**Comment by rotemsd** [comment]
we realized that no.
